image:
 name: node:slim
 
services:
  - name: mongo:6.0
    alias: mongodb

variables:
  MONGO_HOST: mongodb

before_script:
  - apt update
  - npm install -g nodemon newman

stages:
  - build
  - api-server

build:
  stage: build
  script:
   - cd api
   - npm install
  artifacts:
    paths:
      - api/node_modules

api-server:
  stage: api-server
  script:
    - cd api
    - >-
      NODE_ENV="development"
      DATABASE_URL="mongodb://$MONGO_HOST"
      PORT=8888
      JWT_SECRET_KEY="ZT4X3n2pgTejYYUjQQbrlemEuhPjIWAl"
      JWT_EXPIRES_IN="30d"
      npm run dev &
    - echo "Waiting for API server to start..."
    - sleep 10
    - echo "Running newman tests..."
    - >-
      newman run
      -e ../testing/Chas_Challenge.postman_environment.json
      ../testing/Chas_Challenge.postman_collection.json
  dependencies:
    - build
    