services:
  - name: mongo:6.0
    alias: mongodb

variables:
  MONGO_HOST: mongodb

stages:
  - build
  - test

build:
  image: node:slim
  stage: build
  script:
   - cd api
   - npm install
  artifacts:
    paths:
      - api/node_modules

api-test:
  stage: test
  image: node:slim
  before_script:
    - npm install -g nodemon newman
  script:
    - cd api
    - >-
        NODE_ENV="development"
        DATABASE_URL="mongodb://$MONGO_HOST"
        PORT=8888
        JWT_SECRET_KEY="qWertyRandomString"
        JWT_EXPIRES_IN="30d"
        npm run dev &
    - >-
        echo "Waiting for API server to start..."
        newman run
        -e ../testing/Chas_Challenge.postman_environment.json
        ../testing/Chas_Challenge.postman_collection.json
