image:
 name: node:slim

before_script:
  - npm install -g nodemon

stages:
  - build
  - test

build:
  stage: build
  script:
   - cd api
   - npm install
   - npm run dev

test:
  stage: test
  script:
   - echo "test"
