image:
 name: node:slim

services:
  - name: mongo:6.0

before_script:
  - apt update
  - npm install -g nodemon newman

stages:
  - build
  - test

build:
  stage: build
  script:
   - cd api
   - npm install
   - npm run dev

test:
  stage: test
  script:
   - newman run -e testing/Chas_Challenge.postman_environment.json testing/Chas_Challenge.postman_collection.json
  dependencies:
    - build
