services:
  - name: mongo:6.0
    alias: mongodb

variables:
  MONGO_HOST: mongodb

stages:
  - build
  - test

build:
  image: node:slim
  stage: build
  script:
   - cd api
   - npm install
  artifacts:
    paths:
      - api/node_modules

test:
  stage: test
  image:
    name: postman/newman:alpine
    entrypoint: [""] 
  script:
      - | 
        newman run
        -e ../testing/Chas_Challenge.postman_environment.json
        ../testing/Chas_Challenge.postman_collection.json
  dependencies:
    - build
    