image: node:19-alpine3.16

services:
  - name: mongo:6.0
    alias: mongodb

variables:
  MONGO_HOST: mongodb

stages:
  - build
  - test

build:
  stage: build
  script:
   - cd api
   - npm install
  artifacts:
    paths:
      - api/node_modules
    expire_in: 1 week

api-server:
  stage: test
  before_script:
    - npm install -g nodemon
  script:
    - cd api
    - >-
        NODE_ENV="development"
        DATABASE_URL="mongodb://$MONGO_HOST"
        PORT=8888
        JWT_SECRET_KEY="rOvIhkuJfRGuwsOwZNYP4TeglHPwFhe8"
        JWT_EXPIRES_IN="30d"
        npm run dev &
        sleep 10
  dependencies:
    - build

api-test:
  stage: test
  before_script:
    - npm install -g newman
  script:
    - echo "Waiting for API server to start..."
    - >-
        newman run
        -e testing/Chas_Challenge.postman_environment.json
        testing/Chas_Challenge.postman_collection.json
  needs: [api-server]