name: Mirror and run GitLab CI

# on: [push]
on:
  pull_request:
    types: [closed]
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/<namespace>/<repository>"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "Sm0rezDev"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # Token is valid till the next month
        GITLAB_PROJECT_ID: "45714880"
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}