name: Mirror and run GitLab CI

on:
  pull_request:
    types: [closed]
    branches:
      - deployment
  # push:
  #   branches:
  #     - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "git@gitlab.com:Sm0rezDev/chaschallenge.git ."
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "Sm0rezDev"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
        GITLAB_PROJECT_ID: "45785764" 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
